"""Abstract Base LLM Provider interface."""
from abc import ABC, abstractmethod
from typing import Optional


class BaseLLMProvider(ABC):
    """Contract for Large Language Model generation providers."""

    @abstractmethod
    def generate(
        self,
        prompt: str,
        system_prompt: Optional[str] = None,
        temperature: Optional[float] = None,
        max_tokens: Optional[int] = None,
    ) -> str:
        """Generate a completion for the given prompt and system instructions.
        
        Args:
            prompt: The user query / prompt text.
            system_prompt: Optional system-level instructions constraining behavior.
            temperature: Sampling temperature (0.0 for deterministic factual generation).
            max_tokens: Maximum tokens in the generated response.
            
        Returns:
            The raw text generated by the model.
        """
        pass

    @property
    @abstractmethod
    def model_name(self) -> str:
        """Name of the model being called (e.g. gpt-4o-mini)."""
        pass

